import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "antialiased flex flex-col text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900"
        }
      >
        <header className="px-5 h-[60px] bg-slate-300 dark:bg-slate-800">
          <Header />
        </header>
        <main className="px-5 flex-1 flex">{children}</main>
        <footer className="bg-slate-800 px-10 py-5">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
