import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "antialiased flex flex-col px-5 text-slate-500 dark:text-slate-400 bg-white dark:bg-slate-900"
        }
      >
        <header className="h-[60px]">
          <Header />
        </header>
        <main className="flex-1 flex">{children}</main>
      </body>
    </html>
  );
}
