import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tech Fans : Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + "flex h-screen w-screen"}>
        <div className="antialiased flex flex-col min-h-screen max-h-max w-screen dark:text-slate-400 text-slate-700 bg-slate-100 dark:bg-slate-800">
          <header className="px-5 h-[60px] overflow-x-hidden">
            <Header />
          </header>
          <main className="dark:text-slate-400 text-slate-700 bg-slate-200 dark:bg-slate-950 px-5 flex-1 flex">
            {children}
          </main>
          <footer className="px-10 py-5">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
